version: '3'

services:
    prod:
        container_name: newsletter-kiwi
        image: margotbrun/newsletter-kiwi
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          - NODE_ENV=production
        ports:
          - ${PORT:-80}:80